[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/var/run/supervisord.pid

; ----------------------------
; Laravel App Server
; ----------------------------
[program:laravel]
command=php artisan serve --host=0.0.0.0 --port=10000
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

; ----------------------------
; Reverb WebSocket Server
; ----------------------------
[program:reverb]
command=php artisan reverb:start --host=0.0.0.0 --port=8080
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr